jobs:
  prettier:
    if: startsWith(github.head_ref, 'releases/')
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm format --list-different

name: CI Branches Renovate

on:
  pull_request:
    branches:
      - "renovate/**"
