jobs:
  cta_transition:
    if: startsWith(github.head_ref, 'renovate/')
    name: CTA Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: "${{ secrets.ACCESS_TOKEN }}"
      - uses: ./.github/actions/prepare
      - run: npx create-typescript-app
      - run: git status
      - run: git diff HEAD
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Check in changes from re-running npx create-typescript-app"
          commit_user_email: "bot@create.bingo"
          commit_user_name: "The Friendly Bingo Bot"

name: CTA Renovate

on:
  pull_request:
    branches:
      - main
